const RoutePaths = {
  login: 'Login',
  signUp: 'signup',
  forgotpassword: 'forgotpassword',
  appdrawer: 'appdrawer',
  bottomtab: 'bottomtab',
  home: 'HOME',
  showCase: 'SHOWCASE',
  MarketPlace: 'MARKETPLACE',
  Services: 'SERVICES',
  AboutUs: 'About Us',
  Cart: 'Cart',
  MyAccount: 'My Account',
  Profile: 'Profile',
  editProfile: 'Edit profile',
  changePasswod: 'Change Password',
  notification: 'Notification',
  myPoint: 'My Point',
  wallet: 'Wallet',
  myBookings: 'My Booking',
  savedProduct: 'Saved Product',
  leaveReview: 'Leave Review',
  MyListingScreen: 'MyListingScreen',
  inbox: 'Inbox',
  teamList:'Meet the Team',
  MyLikes:'My Likes',
  TransactionHistory:'TransactionHistory',
  MarketplacePS:'MarketPlacePS',
  temp:'temp',
  //Deata route path
  ShowCaseDetails:'ShowCaseDetails',
  BookingSM:'BookingSM',
  BookingHsm:'BookingHsm',

  Chekout:'Chekout',
  ChekoutHsm:'ChekoutHsm',
  ChekoutCart:'ChekoutCart',
  MarketPlaceDetails:'MarketPlaceDetails',
  CategoriesPage:'CategoriesPage',
  ChatScreenListing:'ChatScreenListing',
  ChattingScreen:'ChattingScreen',
  HomeServiceDetails :'HomeServiceDetails',
  ProductServiceDetails :'ProductServiceDetails',
  OrdersScreen :'OrdersScreen',
  categoryPage :'CategoryPage',
  ChatScreen:'ChatScreen',
  Support:'Support',
  EditListing:'EditListing',
  Booking:'Booking',
  NotificationScreen:'NotificationScreen',
  Buyers:'Buyers',
  AddListing:'AddListing',
  OrderDetails:'OrderDetails'
 
};

export default RoutePaths;
