export const authActions = {
  //Login Action types
  AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  //signup Action types
  AUTH_SIGNUP_REQUEST: 'AUTH_SIGNUP_REQUEST',
  AUTH_SIGNUP_SUCCESS: 'AUTH_SIGNUP_SUCCESS',
  AUTH_SIGNUP_FAILURE: 'AUTH_SIGNUP_FAILURE',
  EMAIL_VERIFICATION_REQUEST:'EMAIL_VERIFICATION_REQUEST',
  EMAIL_VERIFICATION_SUCCESS:'EMAIL_VERIFICATION_SUCCESS,',
  EMAIL_VERIFICATION_FAILURE:'EMAIL_VERIFICATION_FAILURE',
  //forgot  Password Action types
  AUTH_FORGOT_PASS_REQUEST: 'AUTH_FORGOT_PASS_REQUEST',
  AUTH_FORGOT_PASS_SUCCESS: 'AUTH_FORGOT_PASS_SUCCESS',
  AUTH__FORGOT_PASS_FAILURE: 'AUTH__FORGOT_PASS_FAILURE',

  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',

};
