export const FontSize = {
  Font10: 10,
  Font12: 12,
  Font13: 13,
  Font15: 15,
  Font16: 16,
  Font18: 18,
  Font20: 20,
  Font21: 21,
  Font22: 22,
  Font24: 24,
  Font25: 25,
  Font26: 26,
  Font27: 27,
  Font29: 29,
  Font30: 30,
};

export const Fonts = {
  GilroyBlack: 'Gilroy-Black',
  GilroyBlackItalic: 'Gilroy-BlackItalic',
  GilroyBold: 'Gilroy-Bold',
  GilroyBoldItalic: 'Gilroy-BoldItalic',
  GilroyExtraBold: 'Gilroy-ExtraBold',
  GilroyExtraBoldItalic: 'Gilroy-ExtraBoldItalic',
  GilroyHeavy: 'Gilroy-Heavy',
  GilroyHeavyItalic: 'Gilroy-HeavyItalic',
  GilroyLight: 'Gilroy-Light',
  GilroyLightItalic: 'Gilroy-LightItalic',
  GilroyMedium: 'Gilroy-Medium',
  GilroyMediumItalic: 'Gilroy-MediumItalic',
  GilroyRegular: 'Gilroy-Regular',
  GilroySemiBold: 'Gilroy-SemiBold',
  GilroySemiBoldItalic: 'Gilroy-SemiBoldItalic',
  GilroyThin: 'Gilroy-Thin',
  GilroyThinItalic: 'Gilroy-ThinItalic',
  GilroyUltraLight: 'Gilroy-UltraLight',
  GilroyUltraLightItalic: 'Gilroy-UltraLightItalic',
};
