const string = {
    appName: 'MY APP',
    anotherString: 'Hello',
    logIn: 'Log In',
    username: 'Username',
    password: 'Password',
    Login: 'Login',
    forgetPassword: 'Forget Password ?',
    hi: 'Hello',
    uber: 'Uber',
    getThere: 'Get There.',
    getStarted: 'Get Started',
    getOTP: 'Send OTP',
    registerWithUs: 'Registered with us?',
    register: 'Register',
    Vendor_Registration: 'Vendor Registration',
    goodsSales: 'Goods & Sales Tax - GST',
    uploadDocuments: 'Upload Documents',
    companyPanCard: 'Company PAN Card',
    captureImage: 'Capture an Image',
    previewUploadedDocument: 'Preview Uploaded Document',
    saveProceed: 'Save & Proceed Next',
    supportiveDocuments: 'Supportive Documents Uploaded',
    dashboard_title: 'Make My License',
    uploadedSuccesFully: 'Uploaded Successfully',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmEyNDRjMTY1YWQxODBmNjdmZjM5MDIzNjQyMDJkN2IzMGU5MjdiZjAyMjM3YzlmOWZhNDJhMmQyYWU2ZTNjZjdmYjM5OTYxYmI1NDA5NmYiLCJpYXQiOjE2ODE5MDQ5MTEuMTU4NzkzOTI2MjM5MDEzNjcxODc1LCJuYmYiOjE2ODE5MDQ5MTEuMTU4ODIxMTA1OTU3MDMxMjUsImV4cCI6MTcxMzUyNzMxMS4xNDQzMTMwOTcwMDAxMjIwNzAzMTI1LCJzdWIiOiIxNCIsInNjb3BlcyI6W119.C_jOyaxi3XUAQUzISxVWfvWtdDc03mLdS5kQU0WPGEOYV4JCw4FA9wuOY8ZKeu12xdrqOHjs1IrpPu2FDFMUeI0BCLc1BdN5YFkmt-NC7TokqFv7xMKSMut5rz_vi_jovSB7rqtinJdXPBlqGKAyUMoXAnFBGCGPY3boeyPSHOw8hQheYxEYmvYj097b9dd7LUOgRbxRZhkKFHlgP5iEx_3RSavn3rp38SiU7awZqH5W2Tb6A6Te9TAFdPfR4dLd6JWOvoDQa7YFD3EYH_7WM-dQRbJRqeOkwXT-OyKs1wgZMizMrKAjOtp80sJ2G1V_TLMZzGnDAZxl36kOeLiON2bgJ13VKRQ7POQO06V1aVNebPC39J22mCejNn4IYXyiFUuSKTBmfIXKy1krCHOp24CEV9UI8TDz0nI8twd71_yFTxD0BWN8_eiuSni23pdMjpB1pVwOd_Sv1Rnk0ykM662j96ESSbI1vsQyb7rt2Ih-PKRwEmhyWx1MmcKICpCvpaVg0Gj_2KCZ4JSHz6Lk3ol2OQxn1o1mCpi-rG_jmpcXlLpdlsCTNkX7JrGL1PA5ewBYIEJJsTfM4x47RCtwgbMGyhvSnTprL-LycB672Kbx6s6h9DuCVGEU1iXT6Cw9g2XQHJLJOsjnfoPbcKB4jDKGWxau5xlwpi0wKi5UNQg',
    needAssistance: 'Need Assistance?',
    updateStatus: '1. Update Status',
    courierDetails: '2. Courier Details',
    paymentDetails: '3. Payment Details',
    updateStatusKey: 'updateStatus',
    courierStatusKey: 'courierDetails',
    paymentKey: 'paymentKey',
    selectStatus: 'Select Status',
    subStatus: 'Sub Status',
    courierName: 'Enter Courier Name',
    enterConsignment: 'Enter Consignment Number',
    uploadChallan: 'Upload Courier Challan',
    comment: 'Comment',
    enterAmnt: 'Enter Amount (In INR)',
    enterNotes: 'Enter Notes (If Any)',
    uploadPaymentChallan: 'Upload Payment Challan',
    PaymentTransactions: 'Payment Transactions',
    submit: 'Submit',
    viewDetails: 'Update Status',
    courierDetailsTitle: 'Courier Details',
    paymentDetailsTitle: 'Payment Details',
    allianceToken:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjgwYzU1Y2JjNTE2Zjk1MGM3Yzc5NjgyMTdkMTMwOTk1MDhmMWU4Yjg5NDY1N2M1NDRhNWZjOTJhODRhNmU3OTkzYWJjZmU5OTU4MzFkZTYiLCJpYXQiOjE2ODEzNTQwNzMuMDUxODMwMDUzMzI5NDY3NzczNDM3NSwibmJmIjoxNjgxMzU0MDczLjA1MTg0MTAyMDU4NDEwNjQ0NTMxMjUsImV4cCI6MTcxMjk3NjQ3My4wMzk0NzcxMDk5MDkwNTc2MTcxODc1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.I9XLpxEB36r67wARGKgeKEGS9duEhIKJxCv53xg7IO7Rbr33HRz0dNVgRxEMWWtpeVf86c1xHhfWl86IDc4uAxQXBMX-xHT7sYOg5OASlgaRTUjiqX23zq02J0Zq5k8fLa-rZMckv_Ygtk-uIEdAjBAGOSyXB_e_C285b_XypKdOCp8TQ6BbzgF87AiiJsH_nEp3HOdMIYSCxuIk90iB3HbT-MWgIvkg5C8Y5daUTB02KlBq-xP9N5hYf0cCAGh2cXHUjfudVs07i4vwUrMIGeNQ9yzpvsJWBOyCnn1YJhEiyB2YNOd4_PjOibf3sBsq8psleLWkm5QpDK8b1QjfBBquZYJbCL67x1Gp1X9xUs3ivGz0BtKKn5B3m8aDXwL5zWNU8-BxVYL9jS7JJAR0vhwM1gUEKORmurFzjTZsb8hGguwTYvp7OzIz02lCRr4PEDobfSrgrflGZmrcqFyjdg4s8g2APuItqrtRzyL2UkEmeBGOxcDwpL6MwIlb8UyAhmntBqwbNw0acV_0TdVhquNR9rsvC1q0105e9_S3fdRk5QsOVDAduGMLfGIEQewx_xGJpBd3RisbigEo-wX-PfFVRrLp6O1ZSyu_5tdaiJnFQeGy1A9CeWkTnKT2f-gDvx8V5aWSD1JKjjrrHbFEf4vaDY4ws3RQEv66ExTI5SM',
  };
  
  export default string;
  