export const homeaction = {
  HOME_MARKET_PLACE_REQUEST: 'HOME_MARKET_PLACE_REQUEST',
  HOME_MARKET_PLACE_SUCCESS: 'HOME_MARKET_PLACE_SUCCESS',
  HOME_MARKET_PLACE_FAILURE: 'HOME_MARKET_PLACE_FAILURE',

  HOME_SERIVCE_REQUEST: 'HOME_SERIVCE_REQUEST',
  HOME_SERVICE_SUCCESS: 'HOME_SERVICE_SUCCESS',
  HOME_SERVICE_FAILURE: 'HOME_SERVICE_FAILURE',

  HOME_SHOWCASE_REQUEST: 'HOME_SHOWCASE_REQUEST',
  HOME_SHOWCASE_SUCCESS: 'HOME_SHOWCASE_SUCCESS',
  HOME_SHOWCASE_FAILURE: 'HOME_SHOWCASE_FAILURE',



  USER_IFNO_REQUEST: 'USER_IFNO_REQUEST',
  USER_IFNO_SUCCESS: 'USER_IFNO_SUCCESS',
  USER_IFNO_FAILURE: 'USER_IFNO_FAILURE',

};
